# Generated by Django 5.0.2 on 2024-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jayapp', '0002_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('Residence', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
