# Generated by Django 5.0.2 on 2024-02-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jayapp', '0003_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('CreationDate', models.DateField()),
            ],
        ),
    ]
